name: event-chat

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_data:/etc/letsencrypt
    depends_on:
      - auth-service
      - user-service
      - chat-service
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
      target: prod
    env_file:
      - ./auth-service/.env
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      target: prod
    env_file:
      - ./user-service/.env
    restart: unless-stopped
    depends_on:
      - kafka

  chat-service:
    build:
      context: ./chat-service
      target: prod
    env_file:
      - ./chat-service/.env
    restart: unless-stopped
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

volumes:
  certbot_data: